resolver: lts-13.3

packages:
- '.'
- location:
    git: https://gitlab.imn.htwk-leipzig.de/waldmann/begriff.git
    commit: 39c96629fbf6b5fef18277ecfa3bfe1ac9c791f6
  extra-dep: true

extra-deps:
- graphviz-2999.20.0.3

system-ghc: true
compiler-check: newer-minor
