# if you change this, be sure to change keter.sh as well
resolver: lts-11.11
# resolver: nightly-2017-08-15

packages:
- '.'
- location:
    git: https://gitlab.imn.htwk-leipzig.de/waldmann/begriff.git
    commit: 39c96629fbf6b5fef18277ecfa3bfe1ac9c791f6
  extra-dep: true

extra-deps:
 - graphviz-2999.19.0.0
 - fgl-5.5.4.0

 
system-ghc: true
compiler-check: newer-minor
