stanzas:
  - type: webapp
    env:
      APPROOT: "https://termcomp.imn.htwk-leipzig.de"
      LANG: "en_US.utf8"
      HOME: /home/keter
    exec: ../.stack-work/install/x86_64-linux/lts-13.3/8.6.3/bin/star-exec-presenter
    args:
      - production
    hosts:
      - termcomp.imn.htwk-leipzig.de
      - localhost
      - "127.0.0.1"
  - type: static-files
    hosts:
      - termcomp.imn.htwk-leipzig.de
    root: ../static
